; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:esp-wrover-kit]
; platform = espressif32
; board = esp-wrover-kit
; framework = arduino
; monitor_speed = 115200
; ; upload_protocol = espota ;for anchor - OTA upload -> comment for tag upload (USB)
; ; upload_port = 192.168.1.21 ; IP address of anchor esp32 
; lib_deps =
;     knolleary/PubSubClient
;     DW3000
;      h2zero/NimBLE-Arduino @ ^1.4.2

; build_flags = 
;    -Wno-write-strings
;    -Wno-return-type

; Wybór domyślnego środowiska, kiedy klikasz "Build"
[platformio]
default_envs = anchor_a1

; --------------------------------------
; ŚRODOWISKO 1: TWÓJ TAG (Ten z FreeRTOS i Bluetooth)
; --------------------------------------
[env:tag_mobile]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
upload_port = COM3 
monitor_port = COM3
; Wpisz port, pod którym widać Taga w menedżerze urządzeń:
; upload_protocol = espota ;for anchor - OTA upload -> comment for tag upload (USB)
; upload_port = 192.168.1.21 ; IP address of anchor esp32 
lib_deps =
    knolleary/PubSubClient
    DW3000
     h2zero/NimBLE-Arduino @ ^1.4.2


; Wybierz plik źródłowy dla Taga (jeśli przechowujesz je w innych folderach)
build_src_filter = +<tag.cpp> 

; --------------------------------------
; ŚRODOWISKO 2: TWOJA KOTWICA (Stacjonarna)
; --------------------------------------
[env:anchor_a1]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200

; upload_protocol = espota ;for anchor - OTA upload -> comment for tag upload (USB)
; upload_port = 192.168.1.21 ; IP address of anchor esp32 
lib_deps =
    knolleary/PubSubClient
    DW3000
     h2zero/NimBLE-Arduino @ ^1.4.2

upload_port = COM5
monitor_port = COM5
build_src_filter = +<anchor.cpp> 